flowable:
  database-schema-update: true

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: on
logging:
  pattern:
    console: "%C:%L %m%n"
#  level:
#    root: "debug"
#    org.springframework.web: "debug"
#    org.hibernate: "debug"
#pagehelper.
pagehelper:
  autoDialect: true
  closeConn: true
  hello: \u4F60\u597D
  nihao: Hello
  offset-as-page-num: false